alias ..='cd ..'
alias cdp='cd ~/Projects'
alias cdd='cd ~/Downloads'
alias cdw='cd /media/data/mgao/workspace'
alias grep='grep -Hn --color=always'
alias grepcc='grep -Hn --color=always -B 3 -A 3 -i --include \*.h --include \*.hh --include \*.cpp --include \*.cc --include \*.c'
alias cmake='cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON'
alias duh='du -hs .[^.]*'
